const imgs = ["img/wp(1).jpg",
"img/wp(2).jpg",
"img/wp(3).jpg",
"img/wp(4).jpg",
"img/wp(5).jpg",
"img/wp(6).jpg",
"img/wp(7).jpg",
"img/wp(8).jpg",
"img/wp(9).jpg",
"img/wp(10).jpg",
"img/wp(11).jpg",
"img/wp(12).jpg",
"img/wp(13).jpg",
"img/wp(14).jpg",
"img/wp(15).jpg",
"img/wp(16).jpg",
"img/wp(17).jpg",
"img/wp(18).jpg",
"img/wp(19).jpg",
"img/wp(20).jpg",
"img/wp(21).jpg",
"img/wp(22).jpg",
"img/wp(23).jpg",
"img/wp(24).jpg",
"img/wp(25).jpg",
"img/wp(26).jpg",
"img/wp(27).jpg",
"img/wp(28).jpg",
"img/wp(29).jpg",
"img/wp(30).jpg",
"img/wp(31).jpg",
"img/wp(1).webp",
"img/wp(2).webp",
];

const imgNum = Math.floor(Math.random()*imgs.length);
document.body.style.backgroundImage =`url('${imgs[imgNum]}')`;
